namespace: staging
frontend:
  replicaCount: 1
  image:
    repository: fakay96/coupon-frontend
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    host: app-staging.dishpal.ai
  resources:
    requests:
      memory: "192Mi"
      cpu: "150m"
    limits:
      memory: "384Mi"
      cpu: "300m"
  env:
    apiUrl: "https://api.staging.example.com"
    environment: "staging"


ingress:
  host: app-staging.dishpal.ai
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - app-staging.dishpal.ai
      secretName: app-staging-dishpal-ai-tls