apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: backend
    release: {{ .Release.Name }}
spec:
  type: "{{ .Values.backend.service.type | default "ClusterIP" }}"
  ports:
    - port: {{ .Values.backend.service.port | default 8000 }}
      targetPort: {{ .Values.backend.service.port | default 8000 }}
      protocol: TCP
  selector:
    app: backend
    release: {{ .Release.Name }}
